reports:

    all_sites_by_browser_family_and_major:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    all_sites_by_browser_family_and_major_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    all_sites_by_browser_family_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    all_sites_by_os_and_browser:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    all_sites_by_os_and_browser_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    all_sites_by_os_family_and_major:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    all_sites_by_os_family_and_major_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    all_sites_by_os_family_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    mobile_site_by_browser_family_and_major:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    mobile_site_by_browser_family_and_major_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    mobile_site_by_browser_family_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    mobile_site_by_os_family_and_major:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    mobile_site_by_os_family_and_major_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    mobile_site_by_os_family_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    desktop_site_by_os_family_and_major:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    desktop_site_by_os_family_and_major_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    desktop_site_by_os_family_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    desktop_site_by_browser_family_and_major_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    desktop_site_by_browser_family_percent:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week

    desktop_site_by_browser_family_and_major:
        type: script
        granularity: weeks
        starts: 2015-06-07
        lag: 86400 # wait 1 day to compute last week
